# Generated by Django 3.1.6 on 2021-02-23 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.dataset')),
            ],
            options={
                'verbose_name': 'ImageUploader',
                'verbose_name_plural': 'ImageUploader',
            },
        ),
    ]
