# Generated by Django 3.1.6 on 2021-03-16 04:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0005_auto_20210312_1454'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('editor', '0005_auto_20210315_1753'),
        ('annotator', '0004_auto_20210312_1454'),
        ('cms', '0005_auto_20210312_1454'),
        ('logger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField(auto_now_add=True)),
                ('object', models.CharField(choices=[('LABELED', 'LABELED'), ('LOGIN', 'LOGIN'), ('MEMBER', 'MEMBER'), ('PROJECT', 'PROJECT'), ('WORKITEM', 'WORKITEM')], max_length=64)),
                ('action', models.CharField(choices=[('SUBMITED', 'SUBMITED'), ('SKIPPED', 'SKIPPED'), ('JOIN', 'JOIN'), ('DATASET', 'DATASET')], max_length=64)),
                ('change_message', models.CharField(max_length=256)),
                ('value', models.JSONField()),
                ('label', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='editor.label')),
                ('labeleditem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='annotator.labeleditem')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.member')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.projects')),
                ('tool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='editor.tool')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workitem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='distributor.workitem')),
            ],
        ),
        migrations.DeleteModel(
            name='UserLog',
        ),
    ]
