# Generated by Django 3.1.6 on 2021-05-13 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0002_auto_20210316_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='value',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
