# Generated by Django 3.1.6 on 2021-03-03 11:35

import backend.apps.editor.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('distributor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabeledItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toolType', models.CharField(choices=[('classification', 'CLASSIFICATION'), ('detection', 'DETECTION')], default=backend.apps.editor.models.TypeToolChoice['CLASSIFICATION'], max_length=64)),
                ('controlType', models.CharField(choices=[('bounding_box', 'BOUNDING_BOX'), ('polygon', 'POLYGON'), ('polyline', 'POLYLINE'), ('point', 'POINT'), ('segmentation', 'SEGMENTATION'), ('radio', 'RADIO'), ('checklist', 'CHECKLIST'), ('text', 'TEXT'), ('dropdown', 'DROPDOWN')], default=backend.apps.editor.models.TypeControlTool['BOUNDING_BOX'], max_length=64)),
                ('className', models.CharField(blank=True, max_length=128, null=True)),
                ('classValue', models.JSONField()),
                ('workitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distributor.workitem')),
            ],
        ),
    ]
