# Generated by Django 3.1.6 on 2021-03-04 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0002_auto_20210303_1835'),
        ('annotator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labeleditem',
            name='classCode',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='labeleditem',
            name='classId',
            field=models.ForeignKey(default=81, on_delete=django.db.models.deletion.CASCADE, to='editor.label'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='labeleditem',
            name='color',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='labeleditem',
            name='index',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
