# Generated by Django 3.1.6 on 2021-03-08 09:06

import backend.apps.editor.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0003_auto_20210308_1606'),
        ('annotator', '0002_auto_20210304_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labeleditem',
            name='classId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='editor.label'),
        ),
        migrations.AlterField(
            model_name='labeleditem',
            name='controlType',
            field=models.CharField(choices=[('BOUNDING_BOX', 'BOUNDING_BOX'), ('POLYGON', 'POLYGON'), ('POLYLINE', 'POLYLINE'), ('POINT', 'POINT'), ('SEGMENTATION', 'SEGMENTATION'), ('RADIO', 'RADIO'), ('CHECKLIST', 'CHECKLIST'), ('TEXT', 'TEXT'), ('DROPDOWN', 'DROPDOWN')], default=backend.apps.editor.models.TypeControlTool['BOUNDING_BOX'], max_length=64),
        ),
        migrations.AlterField(
            model_name='labeleditem',
            name='toolType',
            field=models.CharField(choices=[('CLASSIFICATION', 'CLASSIFICATION'), ('DETECTION', 'DETECTION')], default=backend.apps.editor.models.TypeToolChoice['CLASSIFICATION'], max_length=64),
        ),
    ]
