# Generated by Django 3.1.6 on 2021-04-08 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0004_auto_20210312_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='labeleditem',
            name='trust_score',
            field=models.IntegerField(default=0),
        ),
    ]
