# Generated by Django 3.1.6 on 2021-03-04 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_projectsetting'),
        ('distributor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workitem',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cms.projects'),
            preserve_default=False,
        ),
    ]
