# Generated by Django 3.1.6 on 2021-03-12 07:54

import backend.apps.cms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0004_auto_20210308_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberworkitem',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('ANNOTATION', 'ANNOTATION'), ('VALIDATION', 'VALIDATION'), ('COMPLETED', 'COMPLETED'), ('SKIPPED', 'SKIPPED'), ('SUBMITED', 'SUBMITED'), ('REJECTED', 'REJECTED'), ('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE'), ('INVITED', 'INVITED'), ('REQUESTED', 'REQUESTED'), ('JOINED', 'JOINED')], default=backend.apps.cms.models.StatusChoice['ANNOTATION'], max_length=64),
        ),
        migrations.AlterField(
            model_name='workitem',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('ANNOTATION', 'ANNOTATION'), ('VALIDATION', 'VALIDATION'), ('COMPLETED', 'COMPLETED'), ('SKIPPED', 'SKIPPED'), ('SUBMITED', 'SUBMITED'), ('REJECTED', 'REJECTED'), ('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE'), ('INVITED', 'INVITED'), ('REQUESTED', 'REQUESTED'), ('JOINED', 'JOINED')], default=backend.apps.cms.models.StatusChoice['ANNOTATION'], max_length=64),
        ),
    ]
