# Generated by Django 3.1.6 on 2021-04-06 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_auto_20210319_1507'),
        ('distributor', '0008_auto_20210406_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='queuemember',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.projects'),
        ),
    ]
