# Generated by Django 3.1.6 on 2021-02-23 02:39

import backend.apps.cms.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', backend.apps.cms.models.SafeCharField(max_length=256)),
                ('description', models.CharField(blank=True, max_length=1024, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('annotation', 'ANNOTATION'), ('validation', 'VALIDATION'), ('completed', 'COMPLETED'), ('active', 'ACTIVE'), ('inactive', 'INACTIVE'), ('invited', 'INVITED'), ('requested', 'REQUESTED'), ('joined', 'JOINED')], default=backend.apps.cms.models.StatusChoice['ANNOTATION'], max_length=64)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('reviewer', 'REVIEWER'), ('labeler', 'LABELER'), ('admin', 'ADMIN')], default=backend.apps.cms.models.RoleChoice['LABELER'], max_length=64)),
                ('status', models.CharField(choices=[('annotation', 'ANNOTATION'), ('validation', 'VALIDATION'), ('completed', 'COMPLETED'), ('active', 'ACTIVE'), ('inactive', 'INACTIVE'), ('invited', 'INVITED'), ('requested', 'REQUESTED'), ('joined', 'JOINED')], max_length=64)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cms.projects')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', backend.apps.cms.models.SafeCharField(max_length=256)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('num_photos', models.IntegerField(blank=True, null=True)),
                ('in_type', models.CharField(choices=[('segment', 'SEGMENT'), ('classification', 'CLASSIFICATION'), ('audio', 'AUDIO')], max_length=64)),
                ('status', models.CharField(choices=[('annotation', 'ANNOTATION'), ('validation', 'VALIDATION'), ('completed', 'COMPLETED'), ('active', 'ACTIVE'), ('inactive', 'INACTIVE'), ('invited', 'INVITED'), ('requested', 'REQUESTED'), ('joined', 'JOINED')], default=backend.apps.cms.models.StatusChoice['ACTIVE'], max_length=64)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('projects', models.ManyToManyField(related_name='dataset_list', to='cms.Projects')),
            ],
        ),
    ]
