# Generated by Django 3.1.6 on 2021-03-05 03:01

import backend.apps.cms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_projectsetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('annotation', 'ANNOTATION'), ('validation', 'VALIDATION'), ('completed', 'COMPLETED'), ('skiped', 'SKIPED'), ('rejected', 'REJECTED'), ('active', 'ACTIVE'), ('inactive', 'INACTIVE'), ('invited', 'INVITED'), ('requested', 'REQUESTED'), ('joined', 'JOINED')], default=backend.apps.cms.models.StatusChoice['ACTIVE'], max_length=64),
        ),
        migrations.AlterField(
            model_name='member',
            name='status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('annotation', 'ANNOTATION'), ('validation', 'VALIDATION'), ('completed', 'COMPLETED'), ('skiped', 'SKIPED'), ('rejected', 'REJECTED'), ('active', 'ACTIVE'), ('inactive', 'INACTIVE'), ('invited', 'INVITED'), ('requested', 'REQUESTED'), ('joined', 'JOINED')], max_length=64),
        ),
        migrations.AlterField(
            model_name='projects',
            name='status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('annotation', 'ANNOTATION'), ('validation', 'VALIDATION'), ('completed', 'COMPLETED'), ('skiped', 'SKIPED'), ('rejected', 'REJECTED'), ('active', 'ACTIVE'), ('inactive', 'INACTIVE'), ('invited', 'INVITED'), ('requested', 'REQUESTED'), ('joined', 'JOINED')], default=backend.apps.cms.models.StatusChoice['PENDING'], max_length=64),
        ),
    ]
