# Generated by Django 3.1.6 on 2021-04-08 15:39

import backend.apps.cms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_auto_20210319_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('REVIEWER', 'REVIEWER'), ('LABELER', 'LABELER'), ('ADMIN', 'ADMIN')], default=backend.apps.cms.models.RoleChoice['LABELER'], max_length=64)),
            ],
        ),
        migrations.RemoveField(
            model_name='member',
            name='role',
        ),
        migrations.AddField(
            model_name='member',
            name='role',
            field=models.ManyToManyField(related_name='project_role', to='cms.ProjectRole'),
        ),
    ]
