# Generated by Django 3.1.6 on 2021-04-08 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_auto_20210408_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.ManyToManyField(related_name='member', to='cms.ProjectRole'),
        ),
    ]
