# Generated by Django 3.1.6 on 2021-04-12 15:39

import backend.apps.cms.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_auto_20210408_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsetting',
            name='review_vote',
            field=models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(2)]),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='status',
            field=models.CharField(choices=[('REVIEWING', 'REVIEWING'), ('PENDING', 'PENDING'), ('ANNOTATION', 'ANNOTATION'), ('VALIDATION', 'VALIDATION'), ('COMPLETED', 'COMPLETED'), ('SKIPPED', 'SKIPPED'), ('SUBMITED', 'SUBMITED'), ('REJECTED', 'REJECTED'), ('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE'), ('INVITED', 'INVITED'), ('REQUESTED', 'REQUESTED'), ('JOINED', 'JOINED')], default=backend.apps.cms.models.StatusChoice['ACTIVE'], max_length=64),
        ),
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.ManyToManyField(related_name='members', to='cms.ProjectRole'),
        ),
        migrations.AlterField(
            model_name='member',
            name='status',
            field=models.CharField(choices=[('REVIEWING', 'REVIEWING'), ('PENDING', 'PENDING'), ('ANNOTATION', 'ANNOTATION'), ('VALIDATION', 'VALIDATION'), ('COMPLETED', 'COMPLETED'), ('SKIPPED', 'SKIPPED'), ('SUBMITED', 'SUBMITED'), ('REJECTED', 'REJECTED'), ('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE'), ('INVITED', 'INVITED'), ('REQUESTED', 'REQUESTED'), ('JOINED', 'JOINED')], max_length=64),
        ),
        migrations.AlterField(
            model_name='projects',
            name='status',
            field=models.CharField(choices=[('REVIEWING', 'REVIEWING'), ('PENDING', 'PENDING'), ('ANNOTATION', 'ANNOTATION'), ('VALIDATION', 'VALIDATION'), ('COMPLETED', 'COMPLETED'), ('SKIPPED', 'SKIPPED'), ('SUBMITED', 'SUBMITED'), ('REJECTED', 'REJECTED'), ('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE'), ('INVITED', 'INVITED'), ('REQUESTED', 'REQUESTED'), ('JOINED', 'JOINED')], default=backend.apps.cms.models.StatusChoice['PENDING'], max_length=64),
        ),
    ]
