# Generated by Django 3.1.6 on 2021-05-07 11:43

import backend.apps.cms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0013_member_total_rejected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='status',
            field=models.CharField(choices=[('REVIEWING', 'REVIEWING'), ('REVIEWED', 'REVIEWED'), ('PENDING', 'PENDING'), ('ANNOTATION', 'ANNOTATION'), ('VALIDATION', 'VALIDATION'), ('COMPLETED', 'COMPLETED'), ('SKIPPED', 'SKIPPED'), ('SUBMITED', 'SUBMITED'), ('REJECTED', 'REJECTED'), ('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE'), ('INVITED', 'INVITED'), ('REQUESTED', 'REQUESTED'), ('JOINED', 'JOINED'), ('WAITING', 'WAITING')], default=backend.apps.cms.models.StatusChoice['ACTIVE'], max_length=64),
        ),
        migrations.AlterField(
            model_name='member',
            name='status',
            field=models.CharField(choices=[('REVIEWING', 'REVIEWING'), ('REVIEWED', 'REVIEWED'), ('PENDING', 'PENDING'), ('ANNOTATION', 'ANNOTATION'), ('VALIDATION', 'VALIDATION'), ('COMPLETED', 'COMPLETED'), ('SKIPPED', 'SKIPPED'), ('SUBMITED', 'SUBMITED'), ('REJECTED', 'REJECTED'), ('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE'), ('INVITED', 'INVITED'), ('REQUESTED', 'REQUESTED'), ('JOINED', 'JOINED'), ('WAITING', 'WAITING')], max_length=64),
        ),
        migrations.AlterField(
            model_name='projects',
            name='status',
            field=models.CharField(choices=[('REVIEWING', 'REVIEWING'), ('REVIEWED', 'REVIEWED'), ('PENDING', 'PENDING'), ('ANNOTATION', 'ANNOTATION'), ('VALIDATION', 'VALIDATION'), ('COMPLETED', 'COMPLETED'), ('SKIPPED', 'SKIPPED'), ('SUBMITED', 'SUBMITED'), ('REJECTED', 'REJECTED'), ('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE'), ('INVITED', 'INVITED'), ('REQUESTED', 'REQUESTED'), ('JOINED', 'JOINED'), ('WAITING', 'WAITING')], default=backend.apps.cms.models.StatusChoice['PENDING'], max_length=64),
        ),
    ]
