# Generated by Django 3.1.6 on 2021-05-28 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0014_auto_20210507_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='label_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='member',
            name='skip_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='member',
            name='submit_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='member',
            name='total_time',
            field=models.IntegerField(default=0),
        ),
    ]
