# Generated by Django 3.1.6 on 2021-04-08 13:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0008_auto_20210319_1507'),
        ('annotator', '0005_labeleditem_trust_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkItemVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(1)])),
                ('labeleditem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='annotator.labeleditem')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.member')),
            ],
        ),
    ]
