export const EDITOR_TYPE = {
  IMAGE: "image",
  AUDIO: "audio",
};

export const IMAGE_ANNOTATION_TYPE = {
  CLASSIFICATION: "CLASSIFICATION",
  DETECTION: "DETECTION",
};

export const WORK_ITEM_TYPE = {
  ORIGIN: "ORIGIN",
  OVERLAP: "OVERLAP",
};

export const WORK_ITEM_STATUS = {
  PENDING: "PENDING",
  ANNOTATION: "ANNOTATION",
  VALIDATION: "VALIDATION",
  COMPLETED: "COMPLETED",
  REJECTED: "REJECTED",
  SUBMITTED: 'SUBMITED',
  SKIPPED: "SKIPPED",
  REVIEWING: "REVIEWING",
  REVIEW: "REVIEW"
};

export const QUEUE_STATUS = {
  VALIDATION: "VALIDATION",
  COMPLETED: "COMPLETED",
  REJECTED: "REJECTED",
}

export const DETECTION_CONTROLS = {
  BOUNDING_BOX: "BOUNDING_BOX",
  POLYGON: "POLYGON",
  POLYLINE: "POLYLINE",
  POINT: "POINT",
  SEGMENTATION: "SEGMENTATION",
};

export const CLASSIFICATION_CONTROLS = {
  RADIO: "RADIO",
  CHECKLIST: "CHECKLIST",
  TEXT: "TEXT",
  DROPDOWN: "DROPDOWN",
};

export const PROJECT_MEMBER_ROLES = {
  ADMIN: "ADMIN",
  LABELER: "LABELER",
  REVIEWER: "REVIEWER"
};

export const MEMBER_WORK_ITEM_ROLES = {
  LABELER: "LABELER",
  REVIEWER: "REVIEWER"
};

export const PROJECT_LIST_TYPES = {
  ALL: "ALL",
  JOINED: "JOINED",
  INVITED: "INVITED",
  RELATED: "RELATED",
  AVAILABLE: "AVAILABLE",
};

export const PROJECT_MEMBER_STATUS = {
  JOINED: "JOINED",
  PENDING: "INVITE",
};

export const ACTION_LOG_OBJECTS = {
  USER: "USER",
  PROJECT: "PROJECT",
  WORK_ITEM: "WORK_ITEM",
  LABELED_ITEM: "WORK_ITEM",
};

export const WORKSPACE_MODE = {
  ANNOTATION: 'ANNOTATION',
  REVIEW: 'REVIEW',
  PREVIEW: 'PREVIEW',
  VERIFY: 'VERIFY',
}

export const ACTION_LOG_ACTIONS = {
  // Users
  USER_LOGIN: "LOGIN",
  // Projects
  PROJECT_ADMIN_INVITE: "ADMIN_INVITE",
  PROJECT_LABELER_REQUEST: "LABELER_REQUEST",
  PROJECT_ADMIN_ACCEPT: "ADMIN_ACCEPT",
  PROJECT_ADMIN_REJECT: "ADMIN_REJECT",
  PROJECT_LABELER_ACCEPT: "LABELER_ACCEPT",
  PROJECT_LABELER_REJECT: "LABELER_REJECT",
  PROJECT_CREATE: "CREATE",
  PROJECT_CHANGE_SETTINGS: "CHANGE_SETTINGS",
  PROJECT_ADD_QUEUE: "ADD_QUEUE",
  // Work items
  WORK_ITEM_START: "START",
  WORK_ITEM_SKIP: "SKIP",
  WORK_ITEM_SUBMIT: "SUBMIT",
  WORK_ITEM_REVIEWED: "REVIEWED",
  WORK_ITEM_ACCEPTED: "ACCEPTED",
  WORK_ITEM_REJECTED: "REJECTED",

  // Labeled items
  LABELED_ITEM_CREATED: "CREATED",
};
