# Generated by Django 3.1.6 on 2021-03-03 03:31

import backend.apps.cms.models
import backend.apps.editor.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0002_projectsetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Editor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('image', 'IMAGE'), ('audio', 'AUDIO')], default=backend.apps.editor.models.TypeEditorChoice['IMAGE'], max_length=64)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cms.projects')),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('classification', 'CLASSIFICATION'), ('detection', 'DETECTION')], default=backend.apps.editor.models.TypeToolChoice['CLASSIFICATION'], max_length=64)),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='editor.editor')),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', backend.apps.cms.models.SafeCharField(max_length=256)),
                ('color', models.CharField(blank=True, max_length=64, null=True)),
                ('code', models.CharField(blank=True, max_length=64, null=True)),
                ('tool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='editor.tool')),
            ],
        ),
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.CharField(blank=True, max_length=64, null=True)),
                ('tool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='editor.tool')),
            ],
        ),
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', backend.apps.cms.models.SafeCharField(max_length=256)),
                ('type', models.CharField(choices=[('bounding_box', 'BOUNDING_BOX'), ('polygon', 'POLYGON'), ('polyline', 'POLYLINE'), ('point', 'POINT'), ('segmentation', 'SEGMENTATION'), ('radio', 'RADIO'), ('checklist', 'CHECKLIST'), ('text', 'TEXT'), ('dropdown', 'DROPDOWN')], default=backend.apps.editor.models.TypeControlTool['BOUNDING_BOX'], max_length=32)),
                ('tool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='editor.tool')),
            ],
        ),
    ]
