# Generated by Django 3.1.6 on 2021-03-03 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control',
            name='tool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editor.tool'),
        ),
        migrations.AlterField(
            model_name='label',
            name='tool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editor.tool'),
        ),
        migrations.AlterUniqueTogether(
            name='control',
            unique_together={('tool', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='label',
            unique_together={('tool', 'name')},
        ),
    ]
