# Generated by Django 3.1.6 on 2021-03-08 09:06

import backend.apps.editor.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0002_auto_20210303_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control',
            name='type',
            field=models.CharField(choices=[('BOUNDING_BOX', 'BOUNDING_BOX'), ('POLYGON', 'POLYGON'), ('POLYLINE', 'POLYLINE'), ('POINT', 'POINT'), ('SEGMENTATION', 'SEGMENTATION'), ('RADIO', 'RADIO'), ('CHECKLIST', 'CHECKLIST'), ('TEXT', 'TEXT'), ('DROPDOWN', 'DROPDOWN')], default=backend.apps.editor.models.TypeControlTool['BOUNDING_BOX'], max_length=32),
        ),
        migrations.AlterField(
            model_name='tool',
            name='editor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='editor.editor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tool',
            name='type',
            field=models.CharField(choices=[('CLASSIFICATION', 'CLASSIFICATION'), ('DETECTION', 'DETECTION')], default=backend.apps.editor.models.TypeToolChoice['CLASSIFICATION'], max_length=64),
        ),
    ]
