# Generated by Django 3.1.6 on 2021-03-15 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0003_auto_20210308_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='description',
            field=models.CharField(default='test', max_length=2048),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tool',
            name='name',
            field=models.CharField(default='test', max_length=128),
            preserve_default=False,
        ),
    ]
