# Generated by Django 3.1.6 on 2021-05-11 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0005_auto_20210315_1753'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instruction',
            options={'ordering': ['title']},
        ),
        migrations.RenameField(
            model_name='instruction',
            old_name='tool',
            new_name='editor',
        ),
        migrations.AddField(
            model_name='instruction',
            name='title',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='attachment',
            field=models.FileField(default='NULL', upload_to='instruction/'),
            preserve_default=False,
        ),
    ]
