# Generated by Django 3.1.6 on 2021-05-11 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0014_auto_20210507_1143'),
        ('editor', '0006_auto_20210511_0931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instruction',
            name='editor',
        ),
        migrations.AddField(
            model_name='instruction',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='cms.projects'),
            preserve_default=False,
        ),
    ]
