# Generated by Django 3.1.6 on 2021-05-27 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0007_auto_20210511_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='control',
            name='require',
            field=models.BooleanField(default=False),
        ),
    ]
